modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"

[[mods]]
modId="blastplaster"
version="${version}"
displayName="Blast Plaster"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blast-plaster"
logoFile="logo.png"
authors="tgstyle"
description="Got a Blast? Heal it Fast!"
credits="Thanks to EyZox, Lothrazar for inspiration from CreeperHeal"

[[dependencies.blastplaster]]
modId="neoforge"
type="required"
versionRange="[${version_neoforge_min},)"
ordering="NONE"
side="BOTH"

[[dependencies.blastplaster]]
modId="minecraft"
type="required"
versionRange="[${version_mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.blastplaster]]
modId="dynamictrees"
type = "optional"
versionRange="[${version_dynamictrees_min},)"
ordering="AFTER"
side="BOTH"